# sphinx-math-dollar
# from sphinx_math_dollar import NODE_BLACKLIST
# from docutils.nodes import header
#
# math_dollar_node_blacklist = NODE_BLACKLIST + (header,)

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

# sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('../..'))

import sphinx_rtd_theme
from sphinx_rtd_theme import __version__ as theme_version
from sphinx_rtd_theme import __version_full__ as theme_version_full
from sphinx.locale import _

# -- Project information -----------------------------------------------------

project = "MSCG Net"
copyright = ""
author = "Henry Lao, Manish Kakarla, Pradeep Gummidipundi, Atiya Kailany"
# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx_click",
    "sphinx.ext.autodoc",
    "sphinx.ext.coverage",
    # 'sphinx_math_dollar', # sphinx-math-dollar
    # 'sphinx.ext.mathjax', # sphinx-math-dollar
    "sphinx.ext.napoleon",
]

# sphinx-math-dollar
# mathjax_config = {
#     'tex2jax': {
#         'inlineMath': [ ["\\(","\\)"] ],
#         'displayMath': [["\\[","\\]"] ],
#     },
# }


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"
html_theme_options = {
    'logo_only': True,
    'navigation_depth': 5,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']
